apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: votting-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: votting-app-pod
      labels:
        name: votting-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: votting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
        