apiVersion: v1
kind: Pod
metadata:
  name: votting-app-pod
  labels:
    name: votting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: votting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80